# Generated by Django 5.2.3 on 2025-07-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_pack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pack',
            name='card_pool',
        ),
        migrations.RemoveField(
            model_name='pack',
            name='name',
        ),
        migrations.AddField(
            model_name='pack',
            name='opened',
            field=models.BooleanField(default=False),
        ),
    ]
