# Generated by Django 5.2.3 on 2025-07-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_pack_card_pool_remove_pack_name_pack_opened'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wrestler',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='wrestler',
            name='card',
        ),
        migrations.AddField(
            model_name='wrestler',
            name='cards',
            field=models.ManyToManyField(blank=True, related_name='wrestlers', to='main_app.card'),
        ),
    ]
